name: Lint code

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.json'
      - .github/workflows/lint-code.yml

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run the "npm run lint" command
        run: npm run lint

      - name: Run the "npm run format-check" command
        run: npm run format-check

      - name: Run the "npm run type-check" command
        run: npm run type-check